text = [
    "a photo of drinking water", 
    "a photo of eating a meal/snack", 
    "a photo of brushing teeth", 
    "a photo of brushing hair", 
    "a photo of dropping", 
    "a photo of picking up", 
    "a photo of throwing", 
    "a photo of sitting down", 
    "a photo of standing up (from sitting position)", 
    "a photo of clapping", 
    "a photo of reading", 
    "a photo of writing", 
    "a photo of tearing up paper", 
    "a photo of wearing a jacket", 
    "a photo of taking off a jacket", 
    "a photo of wearing a shoe", 
    "a photo of taking off a shoe", 
    "a photo of wearing glasses", 
    "a photo of taking off glasses", 
    "a photo of putting on a hat/cap", 
    "a photo of taking off a hat/cap", 
    "a photo of cheering up", 
    "a photo of hand waving", 
    "a photo of kicking something", 
    "a photo of reaching into a pocket", 
    "a photo of hopping (one foot jumping)", 
    "a photo of jumping up", 
    "a photo of making a phone call/answering the phone", 
    "a photo of playing with a phone/tablet", 
    "a photo of typing on a keyboard", 
    "a photo of pointing to something with a finger", 
    "a photo of taking a selfie", 
    "a photo of checking the time (from a watch)", 
    "a photo of rubbing two hands together", 
    "a photo of nodding head/bowing", 
    "a photo of shaking head", 
    "a photo of wiping face", 
    "a photo of saluting", 
    "a photo of putting the palms together", 
    "a photo of crossing hands in front (saying stop)", 
    "a photo of sneezing/coughing", 
    "a photo of staggering", 
    "a photo of falling", 
    "a photo of touching head (headache)", 
    "a photo of touching chest (stomachache/heart pain)", 
    "a photo of touching back (backache)", 
    "a photo of touching neck (neckache)", 
    "a photo of nausea or vomiting condition", 
    "a photo of using a fan (with hand or paper)/feeling warm", 
    "a photo of punching/slapping another person", 
    "a photo of kicking another person", 
    "a photo of pushing another person", 
    "a photo of patting the back of another person", 
    "a photo of pointing a finger at the other person", 
    "a photo of hugging another person", 
    "a photo of giving something to another person", 
    "a photo of touching another person's pocket", 
    "a photo of handshaking", 
    "a photo of walking towards each other", 
    "a photo of walking apart from each other", 
    "a photo of putting on headphones", 
    "a photo of taking off headphones", 
    "a photo of shooting at the basket", 
    "a photo of bouncing a ball", 
    "a photo of swinging a tennis bat", 
    "a photo of juggling table tennis balls", 
    "a photo of hushing (quiet)", 
    "a photo of flicking hair", 
    "a photo of giving a thumb up", 
    "a photo of giving a thumb down", 
    "a photo of making an OK sign", 
    "a photo of making a victory sign", 
    "a photo of stapling a book", 
    "a photo of counting money", 
    "a photo of cutting nails", 
    "a photo of cutting paper (using scissors)", 
    "a photo of snapping fingers", 
    "a photo of opening a bottle", 
    "a photo of sniffing (smelling)", 
    "a photo of squatting down", 
    "a photo of tossing a coin", 
    "a photo of folding paper", 
    "a photo of balling up paper", 
    "a photo of playing with a magic cube", 
    "a photo of applying cream on a face", 
    "a photo of applying cream on the back of a hand", 
    "a photo of putting on a bag", 
    "a photo of taking off a bag", 
    "a photo of putting something into a bag", 
    "a photo of taking something out of a bag", 
    "a photo of opening a box", 
    "a photo of moving heavy objects", 
    "a photo of shaking a fist", 
    "a photo of throwing up a cap/hat", 
    "a photo of raising hands (both hands)", 
    "a photo of crossing arms", 
    "a photo of making arm circles", 
    "a photo of swinging arms", 
    "a photo of running in place", 
    "a photo of doing butt kicks (kicking backward)", 
    "a photo of doing a cross toe touch", 
    "a photo of doing a side kick", 
    "a photo of yawning", 
    "a photo of stretching oneself", 
    "a photo of blowing one's nose", 
    "a photo of hitting another person with something", 
    "a photo of wielding a knife towards another person", 
    "a photo of knocking over another person (hitting with the body)", 
    "a photo of grabbing another person’s stuff", 
    "a photo of shooting at another person with a gun", 
    "a photo of stepping on someone's foot", 
    "a photo of giving a high-five", 
    "a photo of cheers and drinking", 
    "a photo of carrying something with another person", 
    "a photo of taking a photo of another person", 
    "a photo of following another person", 
    "a photo of whispering in another person’s ear", 
    "a photo of exchanging things with another person", 
    "a photo of supporting somebody with a hand", 
    "a photo of playing a finger-guessing game (rock-paper-scissors)", 
]

text_sysu=[
    #"a photo of drinking water",
    #"a photo of pouring",
    #"a photo of making a phone call",
    #"a photo of playing with a phone",
    #"a photo of putting on a bag",
    #"a photo of putting something into a bag",
    #"a photo of sitting down",
    #"a photo of moving heavy objects",
    #"a photo of reaching into a pocket",
    #"a photo of taking something out of a wallet",
    #"a photo of mopping",
    #"a photo of sweeping"
    
    "drinking",
    "pouring",
    "calling phone",
    "playing phone",
    "wearing backpacks",
    "packing backpacks",
    "sitting chair",
    "moving chair",
    "taking out wallet",
    "taking from wallet",
    "mopping",
    "sweeping"
]

text_nucla=[
    "pick up with one hand",
    "pick up with two hands",
    "drop trash",
    "walk around",
    "sit down",
    "stand up",
    "donning",
    "doffing",
    "throw",
    "carry"
]